apiVersion: v1
kind: Secret
metadata:
  name: {{ include "http-endpoint-nodemailer.fullname" . }}-config
type: Opaque
stringData: #data must be base64 encoded, stringData is not
  config.yml: |  
    {{- toYaml .Values.config | nindent 4 }}