default: #required structure
  submitPath: /send
  submitPort: 8080
  bodySizeLimit: 100kb #express body-parser->urlencoded.limit
  debugRequests: false
  smtp:
    host: mail.host.com
    port: 25
    auth:
      user: username
      pass: password
  mail:
    from: "fromWhom@mail.com"
    to: "toWhom@mail.com"
    subject: "Form Submitted"
    body: | #handlebars formatting with an express "req.body" object, body has been body-parser (urlencode, json encoded) or multer (multipart) encoded
      <p>Form submission</p>
      <p>{{{json body}}}</p>
  resultPage: | #page after submission
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Submission complete</title>
    </head>
    <body>
        Submission Complete
    </body>
    </html>
  errorPage: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Something went wrong, try again later</title>
    </head>
    <body>
        Something went wrong, try again later
    </body>
    </html>
development: #required structure #overrides defaults based on ENV setting
test: #required structure
production: #required structure